version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: serversage-prometheus
    user: "65534:65534"  # nobody:nobody user
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      serversage-network:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: serversage-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: serversage
      GF_SERVER_ROOT_URL: ${GRAFANA_ROOT_URL}
      GF_SERVER_DOMAIN: ${GRAFANA_DOMAIN}
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_NAME: Keycloak
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid email profile roles offline_access
      GF_AUTH_GENERIC_USE_REFRESH_TOKENS: true
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: email
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: username
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: full_name
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
      GF_AUTH_GENERIC_OAUTH_API_URL: ${KEYCLOAK_API_URL}
      GF_AUTH_SIGNOUT_REDIRECT_URL: ${KEYCLOAK_LOGOUT_URL}?id_token_hint=%{id_token}&post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(roles[*], 'grafana_grafana_admin') && 'GrafanaAdmin' || contains(roles[*], 'grafana_admin') && 'Admin' || contains(roles[*], 'grafana_editor') && 'Editor' || 'Viewer'

    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      serversage-network:
        aliases:
          - grafana

  cloudwatch-exporter:
    image: prom/cloudwatch-exporter:latest
    ports:
      - "9106:9106"
    volumes:
      - ./cloudwatch-exporter:/config
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-east-1
    command:
      - /config/config.yml
    restart: unless-stopped
    networks:
      serversage-network:
        aliases:
          - cloudwatch-exporter

  postgres:
    image: postgres:16
    container_name: postgres_demo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      serversage-network:
        aliases:
          - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: 'keycloak_demo'
    command: start-dev --import-realm 
    environment:
      - KC_HOSTNAME=${KEYCLOAK_PUBLIC_URL}/
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HTTP_ENABLED=true    
      - KC_DB=postgres
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=${POSTGRES_DB}
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - '3002:8080'
    volumes:
      - ./keycloak/realm-import:/opt/keycloak/data/import
    networks:
      serversage-network:
        aliases:
          - keycloak
          - keycloak-public

networks:
  serversage-network:
    driver: bridge
    name: serversage-network
    attachable: true
